In [26]:
import pandas as pd
import numpy as np

df_first = pd.read_excel('/content/HumanResources.JobCandidate.xlsx')
print(df_first.shape) #satır sutun sayısı.

(13, 4)

In [27]:
df_first.isnull().sum() #boş satırların sayısı
df_first.info() #satırların bilgisi
df_first.duplicated().sum() #tekrar eden satır sayısı

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   JobCandidateID    13 non-null     int64
 1   BusinessEntityID  2 non-null      float64
 2   Resume            13 non-null     object
 3   ModifiedDate      13 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 548.0+ bytes

np.int64(0)

In [28]:
df_missing = df_first[df_first["BusinessEntityID"].isnull()]
print("Kayıp sayısı ",len(df_missing))
df_missing

Kayıp sayısı  11

,JobCandidateID,BusinessEntityID,Resume,ModifiedDate
0,1,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23
1,2,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23
2,3,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23
4,5,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23
5,6,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23
6,7,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23
8,9,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23
9,10,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23
10,11,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23
11,12,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23
12,13,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23

In [29]:
df_clean = df_first.copy()
df_clean["BusinessEntityID"] = df_clean["BusinessEntityID"].fillna("Bilinmiyor")
print(df_clean["BusinessEntityID"].isnull().sum()) #0 olmalı
df_clean["BusinessEntityID"].value_counts() #kolondaki değerlerin sayısını gösterir.

0

BusinessEntityID
Bilinmiyor    11
274.0          1
212.0          1
Name: count, dtype: int64

In [40]:
df_first.duplicated().sum() #tekrar sayısı
agains_count = df_first[df_first.duplicated()]
agains_count

Empty DataFrame
Columns: [JobCandidateID, BusinessEntityID, Resume, ModifiedDate]
Index: []

In [45]:
df_first["ModifiedDate"] = pd.to_datetime(df_first["ModifiedDate"], errors="coerce") #tarih dönüşümü
df_first["ModifiedDate"]

df_first["Modified Year"] = df_first["ModifiedDate"].dt.year
df_first["Modified Month"] = df_first["ModifiedDate"].dt.month
df_first["Modified Day"] =  df_first["ModifiedDate"].dt.day
df_first

,JobCandidateID,BusinessEntityID,Resume,ModifiedDate,Modified Year,Modified Month,Modified Day
0,1,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
1,2,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
2,3,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
3,4,274.0,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2013-12-22,2013,12,22
4,5,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
5,6,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
6,7,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
7,8,212.0,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2013-12-22,2013,12,22
8,9,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
9,10,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
10,11,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
11,12,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
12,13,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23

In [49]:
not_logical = df_first[df_first["Modified Year"] > 2027] #mantıklı değil  düzenlenme yılı 2027 olamaz.
not_logical

Empty DataFrame
Columns: [JobCandidateID, BusinessEntityID, Resume, ModifiedDate, Modified Year, Modified Month, Modified Day]
Index: []

In [53]:
import pandas as pd
import numpy as np

#kategoriler
print(df_first["Modified Year"].unique())
print(df_first["Modified Month"].unique())
print(df_first["Modified Day"].unique())
#strip() parantezin içindeki karakterleri metinde temizler.

null_issue = df_first["Resume"].apply(lambda x: x != x.strip()).sum()
null_issue

[2007 2013]
[ 6 12]
[23 22]

np.int64(0)

In [55]:
df_clean = df_first.reset_index(drop=True) #indexi sıfırladı.işleminden sonra indeksi sıfırdan yeniden numaralandırmak gerekir.
df_clean.head()

,JobCandidateID,BusinessEntityID,Resume,ModifiedDate,Modified Year,Modified Month,Modified Day
0,1,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
1,2,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
2,3,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23
3,4,274.0,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2013-12-22,2013,12,22
4,5,NaN,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007,6,23

In [56]:
#temiz veriyi kaydetme
df_clean.to_excel("clean_data.xlsx",index= False) #index false  index sutunun excele yazılmasını engeller.

In [61]:
def clean_data(x):
  df = x.copy()
  df["BusinessEntityID"] = df["BusinessEntityID"].fillna("unknown") #eksikleri doldur
  df["ModifiedDate"] = pd.to_datetime(df["ModifiedDate"], errors="coerce") #tarih dönüşümü yap.
  # Mantık hatasını düzelt: Yılı 2027'den büyük olan satırlardaki 'Modified Year' değerini NaN yap.
  df.loc[df["Modified Year"] > 2027, "Modified Year"] = np.nan
  #tekrar eden kayıtlar veriyi bozuyorsa düzenle.
  df = df.reset_index(drop=True) #indexi sıfırla.
  return df

df_result = clean_data(df_first)
df_result.head()

,JobCandidateID,BusinessEntityID,Resume,ModifiedDate,Modified Year,Modified Month,Modified Day
0,1,unknown,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007.0,6,23
1,2,unknown,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007.0,6,23
2,3,unknown,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007.0,6,23
3,4,274.0,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2013-12-22,2013.0,12,22
4,5,unknown,"<ns:Resume xmlns:ns=""http://schemas.microsoft....",2007-06-23,2007.0,6,23