In [73]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.2.2
2.0.2

In [74]:
series = pd.Series([1,2,3,4,5,"","İbrahim"], name = "Serie") #Series oluşturma
print(series)

0          1
1          2
2          3
3          4
4          5
5
6    İbrahim
Name: Serie, dtype: object

In [75]:
df = pd.read_json("/content/features.json")
print("Boyut: ", df.shape)
df.head()

Boyut:  (196, 1)

                0
0  last_known_tvt
1         pf_ancc
2     pf_ancc_std
3   pf_ancc_delta
4            pf_z

In [76]:
df = pd.read_excel("/content/Sales.Store.xlsx")
print("Boyut: ", df.shape)
df.head()

Boyut:  (701, 6)

,BusinessEntityID,Name,SalesPersonID,Demographics,rowguid,ModifiedDate
0,292,Next-Door Bike Store,279,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",A22517E3-848D-4EBE-B9D9-7437F3432304,2014-09-12
1,294,Professional Sales and Service,276,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",B50CA50B-C601-4A13-B07E-2C63862D71B4,2014-09-12
2,296,Riders Company,277,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",337C3688-1339-4E1A-A08A-B54B23566E49,2014-09-12
3,298,The Bike Mechanics,275,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",7894F278-F0C8-4D16-BD75-213FDBF13023,2014-09-12
4,300,Nationwide Supply,286,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",C3FC9705-A8C4-4F3A-9550-EB2FA4B7B64D,2014-09-12

In [77]:
df = pd.read_csv("data.csv")
print("Boyut: ", df.shape)
df.head()

Boyut:  (32, 5)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [78]:
df.info(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [79]:
df.head() #ilk 5 satır gelir.

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [80]:
df.tail() # son 5 satır gelir.

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [81]:
df.shape #satır ve sutun sayılarını verir.

(32, 5)

In [82]:
df.describe() #datasetin sayısal istatiklerini verir.

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [83]:
df.columns #kolon isimlerini verir.

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [84]:
df.dtypes #kolonların tiplerini verir.
df["Calories"]

0     409.1
1     479.0
2     340.0
3     282.4
4     406.0
5     300.0
6     374.0
7     253.3
8     195.1
9     269.0
10    329.3
11    250.7
12    250.7
13    345.3
14    379.3
15    275.0
16    215.2
17    300.0
18      NaN
19    323.0
20    243.0
21    364.2
22    282.0
23    300.0
24    246.0
25    334.5
26    250.0
27    241.0
28      NaN
29    280.0
30    380.3
31    243.0
Name: Calories, dtype: float64

In [85]:
print(df["Maxpulse"].nunique()) #kolonda kaç farklı değer var
print(df["Maxpulse"].unique()) #kolonda hangi değerler


df[["Maxpulse","Date","Calories"]].info(4)
df[df["Calories"] == 300.0].head(1)
df[df["Calories"] > 300 & (df["Duration"] > 45)]

24
[130 145 135 175 148 127 136 134 133 124 147 120 128 132 123 112 125 131
 119 101 126 118 129 115]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Maxpulse  32 non-null     int64
 1   Date      31 non-null     object
 2   Calories  30 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 900.0+ bytes

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [98]:
df['yeni kolon'] = (df["Maxpulse"] - df["Pulse"]).round(1)
df

,Duration,Date,Pulse,Maxpulse,Calories,yeni kolon,yeni kolon 2
0,60,'2020/12/01',110,130,409.1,20,4.091
1,60,'2020/12/02',117,145,479.0,28,4.790
2,60,'2020/12/03',103,135,340.0,32,3.400
3,45,'2020/12/04',109,175,282.4,66,2.824
4,45,'2020/12/05',117,148,406.0,31,4.060
5,60,'2020/12/06',102,127,300.0,25,3.000
6,60,'2020/12/07',110,136,374.0,26,3.740
7,450,'2020/12/08',104,134,253.3,30,2.533
8,30,'2020/12/09',109,133,195.1,24,1.951
9,60,'2020/12/10',98,124,269.0,26,2.690
10,60,'2020/12/11',103,147,329.3,44,3.293
11,60,'2020/12/12',100,120,250.7,20,2.507
12,60,'2020/12/12',100,120,250.7,20,2.507
13,60,'2020/12/13',106,128,345.3,22,3.453
14,60,'2020/12/14',104,132,379.3,28,3.793
15,60,'2020/12/15',98,123,275.0,25,2.750
16,60,'2020/12/16',98,120,215.2,22,2.152
17,60,'2020/12/17',100,120,300.0,20,3.000
18,45,'2020/12/18',90,112,NaN,22,NaN
19,60,'2020/12/19',103,123,323.0,20,3.230
20,45,'2020/12/20',97,125,243.0,28,2.430
21,60,'2020/12/21',108,131,364.2,23,3.642
22,45,NaN,100,119,282.0,19,2.820
23,60,'2020/12/23',130,101,300.0,-29,3.000
24,45,'2020/12/24',105,132,246.0,27,2.460
25,60,'2020/12/25',102,126,334.5,24,3.345
26,60,20201226,100,120,250.0,20,2.500
27,60,'2020/12/27',92,118,241.0,26,2.410
28,60,'2020/12/28',103,132,NaN,29,NaN
29,60,'2020/12/29',100,132,280.0,32,2.800
30,60,'2020/12/30',102,129,380.3,27,3.803
31,60,'2020/12/31',92,115,243.0,23,2.430

In [87]:
#apply() kullanrak kolona işlemler uygulanmıuş şekilde veri atabilirsin.
df["yeni kolon 2"] = df['Calories'].apply(lambda x: x/100)
df

,Duration,Date,Pulse,Maxpulse,Calories,yeni kolon,yeni kolon 2
0,60,'2020/12/01',110,130,409.1,20,4.091
1,60,'2020/12/02',117,145,479.0,28,4.790
2,60,'2020/12/03',103,135,340.0,32,3.400
3,45,'2020/12/04',109,175,282.4,66,2.824
4,45,'2020/12/05',117,148,406.0,31,4.060
5,60,'2020/12/06',102,127,300.0,25,3.000
6,60,'2020/12/07',110,136,374.0,26,3.740
7,450,'2020/12/08',104,134,253.3,30,2.533
8,30,'2020/12/09',109,133,195.1,24,1.951
9,60,'2020/12/10',98,124,269.0,26,2.690
10,60,'2020/12/11',103,147,329.3,44,3.293
11,60,'2020/12/12',100,120,250.7,20,2.507
12,60,'2020/12/12',100,120,250.7,20,2.507
13,60,'2020/12/13',106,128,345.3,22,3.453
14,60,'2020/12/14',104,132,379.3,28,3.793
15,60,'2020/12/15',98,123,275.0,25,2.750
16,60,'2020/12/16',98,120,215.2,22,2.152
17,60,'2020/12/17',100,120,300.0,20,3.000
18,45,'2020/12/18',90,112,NaN,22,NaN
19,60,'2020/12/19',103,123,323.0,20,3.230
20,45,'2020/12/20',97,125,243.0,28,2.430
21,60,'2020/12/21',108,131,364.2,23,3.642
22,45,NaN,100,119,282.0,19,2.820
23,60,'2020/12/23',130,101,300.0,-29,3.000
24,45,'2020/12/24',105,132,246.0,27,2.460
25,60,'2020/12/25',102,126,334.5,24,3.345
26,60,20201226,100,120,250.0,20,2.500
27,60,'2020/12/27',92,118,241.0,26,2.410
28,60,'2020/12/28',103,132,NaN,29,NaN
29,60,'2020/12/29',100,132,280.0,32,2.800
30,60,'2020/12/30',102,129,380.3,27,3.803
31,60,'2020/12/31',92,115,243.0,23,2.430

In [88]:
df.rename(columns={"Date":"Tarih"}) #kolon adı değiştirme

,Duration,Tarih,Pulse,Maxpulse,Calories,yeni kolon,yeni kolon 2
0,60,'2020/12/01',110,130,409.1,20,4.091
1,60,'2020/12/02',117,145,479.0,28,4.790
2,60,'2020/12/03',103,135,340.0,32,3.400
3,45,'2020/12/04',109,175,282.4,66,2.824
4,45,'2020/12/05',117,148,406.0,31,4.060
5,60,'2020/12/06',102,127,300.0,25,3.000
6,60,'2020/12/07',110,136,374.0,26,3.740
7,450,'2020/12/08',104,134,253.3,30,2.533
8,30,'2020/12/09',109,133,195.1,24,1.951
9,60,'2020/12/10',98,124,269.0,26,2.690
10,60,'2020/12/11',103,147,329.3,44,3.293
11,60,'2020/12/12',100,120,250.7,20,2.507
12,60,'2020/12/12',100,120,250.7,20,2.507
13,60,'2020/12/13',106,128,345.3,22,3.453
14,60,'2020/12/14',104,132,379.3,28,3.793
15,60,'2020/12/15',98,123,275.0,25,2.750
16,60,'2020/12/16',98,120,215.2,22,2.152
17,60,'2020/12/17',100,120,300.0,20,3.000
18,45,'2020/12/18',90,112,NaN,22,NaN
19,60,'2020/12/19',103,123,323.0,20,3.230
20,45,'2020/12/20',97,125,243.0,28,2.430
21,60,'2020/12/21',108,131,364.2,23,3.642
22,45,NaN,100,119,282.0,19,2.820
23,60,'2020/12/23',130,101,300.0,-29,3.000
24,45,'2020/12/24',105,132,246.0,27,2.460
25,60,'2020/12/25',102,126,334.5,24,3.345
26,60,20201226,100,120,250.0,20,2.500
27,60,'2020/12/27',92,118,241.0,26,2.410
28,60,'2020/12/28',103,132,NaN,29,NaN
29,60,'2020/12/29',100,132,280.0,32,2.800
30,60,'2020/12/30',102,129,380.3,27,3.803
31,60,'2020/12/31',92,115,243.0,23,2.430

In [92]:
df.sort_values("Calories",ascending=False)[["Date","Calories"]] #kolona göre sıralama

            Date  Calories
1   '2020/12/02'     479.0
0   '2020/12/01'     409.1
4   '2020/12/05'     406.0
30  '2020/12/30'     380.3
14  '2020/12/14'     379.3
6   '2020/12/07'     374.0
21  '2020/12/21'     364.2
13  '2020/12/13'     345.3
2   '2020/12/03'     340.0
25  '2020/12/25'     334.5
10  '2020/12/11'     329.3
19  '2020/12/19'     323.0
23  '2020/12/23'     300.0
5   '2020/12/06'     300.0
17  '2020/12/17'     300.0
3   '2020/12/04'     282.4
22           NaN     282.0
29  '2020/12/29'     280.0
15  '2020/12/15'     275.0
9   '2020/12/10'     269.0
7   '2020/12/08'     253.3
11  '2020/12/12'     250.7
12  '2020/12/12'     250.7
26      20201226     250.0
24  '2020/12/24'     246.0
31  '2020/12/31'     243.0
20  '2020/12/20'     243.0
27  '2020/12/27'     241.0
16  '2020/12/16'     215.2
8   '2020/12/09'     195.1
18  '2020/12/18'       NaN
28  '2020/12/28'       NaN

In [96]:
df.groupby("Duration")["Calories"].mean().sort_values(ascending=False)

Duration
60     314.46087
45     291.88000
450    253.30000
30     195.10000
Name: Calories, dtype: float64

In [99]:
df.groupby("Duration").agg(toplam_kalori = ("Calories", "sum")).sort_values("toplam_kalori",ascending=False)

          toplam_kalori
Duration
60               7232.6
45               1459.4
450               253.3
30                195.1

In [105]:
df_first = df[df["Calories"] == 300.0]
df_second = df[df["Duration"] == 45]
df_united = pd.concat([df_first, df_second]) #list olarak aldıklarını birleştirir.
df_united

,Duration,Date,Pulse,Maxpulse,Calories,yeni kolon,yeni kolon 2
5,60,'2020/12/06',102,127,300.0,25,3.000
17,60,'2020/12/17',100,120,300.0,20,3.000
23,60,'2020/12/23',130,101,300.0,-29,3.000
3,45,'2020/12/04',109,175,282.4,66,2.824
4,45,'2020/12/05',117,148,406.0,31,4.060
18,45,'2020/12/18',90,112,NaN,22,NaN
20,45,'2020/12/20',97,125,243.0,28,2.430
22,45,NaN,100,119,282.0,19,2.820
24,45,'2020/12/24',105,132,246.0,27,2.460

In [108]:
durations = pd.DataFrame({
    "Duration": df["Duration"].dropna().unique()
})

durations['duration'] = durations['Duration'].apply(lambda x: x/100)

df_area = pd. merge(df,durations,on="Duration") #verilen kolonda tabloları birleştirir
df_area

,Duration,Date,Pulse,Maxpulse,Calories,yeni kolon,yeni kolon 2,duration
0,60,'2020/12/01',110,130,409.1,20,4.091,0.60
1,60,'2020/12/02',117,145,479.0,28,4.790,0.60
2,60,'2020/12/03',103,135,340.0,32,3.400,0.60
3,45,'2020/12/04',109,175,282.4,66,2.824,0.45
4,45,'2020/12/05',117,148,406.0,31,4.060,0.45
5,60,'2020/12/06',102,127,300.0,25,3.000,0.60
6,60,'2020/12/07',110,136,374.0,26,3.740,0.60
7,450,'2020/12/08',104,134,253.3,30,2.533,4.50
8,30,'2020/12/09',109,133,195.1,24,1.951,0.30
9,60,'2020/12/10',98,124,269.0,26,2.690,0.60
10,60,'2020/12/11',103,147,329.3,44,3.293,0.60
11,60,'2020/12/12',100,120,250.7,20,2.507,0.60
12,60,'2020/12/12',100,120,250.7,20,2.507,0.60
13,60,'2020/12/13',106,128,345.3,22,3.453,0.60
14,60,'2020/12/14',104,132,379.3,28,3.793,0.60
15,60,'2020/12/15',98,123,275.0,25,2.750,0.60
16,60,'2020/12/16',98,120,215.2,22,2.152,0.60
17,60,'2020/12/17',100,120,300.0,20,3.000,0.60
18,45,'2020/12/18',90,112,NaN,22,NaN,0.45
19,60,'2020/12/19',103,123,323.0,20,3.230,0.60
20,45,'2020/12/20',97,125,243.0,28,2.430,0.45
21,60,'2020/12/21',108,131,364.2,23,3.642,0.60
22,45,NaN,100,119,282.0,19,2.820,0.45
23,60,'2020/12/23',130,101,300.0,-29,3.000,0.60
24,45,'2020/12/24',105,132,246.0,27,2.460,0.45
25,60,'2020/12/25',102,126,334.5,24,3.345,0.60
26,60,20201226,100,120,250.0,20,2.500,0.60
27,60,'2020/12/27',92,118,241.0,26,2.410,0.60
28,60,'2020/12/28',103,132,NaN,29,NaN,0.60
29,60,'2020/12/29',100,132,280.0,32,2.800,0.60
30,60,'2020/12/30',102,129,380.3,27,3.803,0.60
31,60,'2020/12/31',92,115,243.0,23,2.430,0.60

In [120]:
calorie_summary_to_Date = df.groupby("Date").agg(
    total_calories = ("Calories", "sum"),
    average_calories = ("Calories", "mean"),
    max_calories = ("Calories", "max"),
    min_calories = ("Calories", "min"),
    count_calories = ("Calories", "count")
)
print(calorie_summary_to_Date)
print("ortalama kalorisi en fazla olan gün: ", calorie_summary_to_Date["average_calories"].idxmax()) #en fazla olanı bulur
print("ortalama kalorisi en düşük olan gün: ", calorie_summary_to_Date["average_calories"].idxmin()) #en az olanı bulur

              total_calories  average_calories  max_calories  min_calories  \
Date
'2020/12/01'           409.1             409.1         409.1         409.1
'2020/12/02'           479.0             479.0         479.0         479.0
'2020/12/03'           340.0             340.0         340.0         340.0
'2020/12/04'           282.4             282.4         282.4         282.4
'2020/12/05'           406.0             406.0         406.0         406.0
'2020/12/06'           300.0             300.0         300.0         300.0
'2020/12/07'           374.0             374.0         374.0         374.0
'2020/12/08'           253.3             253.3         253.3         253.3
'2020/12/09'           195.1             195.1         195.1         195.1
'2020/12/10'           269.0             269.0         269.0         269.0
'2020/12/11'           329.3             329.3         329.3         329.3
'2020/12/12'           501.4             250.7         250.7         250.7
'2020/12/13'           345.3             345.3         345.3         345.3
'2020/12/14'           379.3             379.3         379.3         379.3
'2020/12/15'           275.0             275.0         275.0         275.0
'2020/12/16'           215.2             215.2         215.2         215.2
'2020/12/17'           300.0             300.0         300.0         300.0
'2020/12/18'             0.0               NaN           NaN           NaN
'2020/12/19'           323.0             323.0         323.0         323.0
'2020/12/20'           243.0             243.0         243.0         243.0
'2020/12/21'           364.2             364.2         364.2         364.2
'2020/12/23'           300.0             300.0         300.0         300.0
'2020/12/24'           246.0             246.0         246.0         246.0
'2020/12/25'           334.5             334.5         334.5         334.5
'2020/12/27'           241.0             241.0         241.0         241.0
'2020/12/28'             0.0               NaN           NaN           NaN
'2020/12/29'           280.0             280.0         280.0         280.0
'2020/12/30'           380.3             380.3         380.3         380.3
'2020/12/31'           243.0             243.0         243.0         243.0
20201226               250.0             250.0         250.0         250.0

              count_calories
Date
'2020/12/01'               1
'2020/12/02'               1
'2020/12/03'               1
'2020/12/04'               1
'2020/12/05'               1
'2020/12/06'               1
'2020/12/07'               1
'2020/12/08'               1
'2020/12/09'               1
'2020/12/10'               1
'2020/12/11'               1
'2020/12/12'               2
'2020/12/13'               1
'2020/12/14'               1
'2020/12/15'               1
'2020/12/16'               1
'2020/12/17'               1
'2020/12/18'               0
'2020/12/19'               1
'2020/12/20'               1
'2020/12/21'               1
'2020/12/23'               1
'2020/12/24'               1
'2020/12/25'               1
'2020/12/27'               1
'2020/12/28'               0
'2020/12/29'               1
'2020/12/30'               1
'2020/12/31'               1
20201226                   1
ortalama kalorisi en fazla olan gün:  '2020/12/02'
ortalama kalorisi en düşük olan gün:  '2020/12/09'